- docs/how-to-use-monty/tutorials.md
Fixes a clumsy typo in `tutorials.md`.
> A typo in tutorials.md

- .github/workflows/cla.yml
The GITHUB_TOKEN is read-only by default in the public repository. This update grants the `cla-assistant` configured in the `cla.yml` permission to create a comment on the Pull Request it is checking. This way, the `cla-assistant` can notify the Contributor to sign the CLA and provide the link.
> ci: grant cla-assistant ability to write comments on issues and PRs

- docs/overview/application-criteria.md
> Docs: rename title to match slug after slug change

- docs/how-to-use-monty/getting-started.md
- environment_arm64.yml
trying to activate the (mini)conda environment fails with the commands described in the [environment_arm64.yml]([environment_arm64.yml):
```shell
% conda init
no change     /opt/homebrew/Caskroom/miniconda/base/condabin/conda
...
No action taken.
% conda activate tbp.monty
CondaError: Run 'conda init' before 'conda activate'
```
the internet suggests a quick-fix, commented in the proposed change
Downloading the habitat as described in the readme fails due to a wrong python module:
```shell
% python -m habitat_sim.utils.environments_download --uids ycb --data-path ~/tbp/data/habitat
/opt/homebrew/Caskroom/miniconda/base/envs/tbp.monty/bin/python: No module named habitat_sim.utils.environments_download
```
The download works when switching to the `datasets_download` module
CLA should have …
> Fix first experiment run docs

- docs/overview/benchmark-experiments.md
This pull request adds instructions for how to download `worldimages` data for use with Monty-Meets-World benchmarks.
> docs: add instructions for downloading worldimages

- docs/how-to-use-monty/getting-started.md
Current docs hint that there may be other ways to install Monty besides Conda. This pull request clarifies that Conda is the only supported way of setting up Monty.
> docs: clarify conda is required for installation

- docs/contributing/style-guide.md
This pull request adds the current GitHub Actions naming convention to the Style Guide for reference.
> docs: GitHub Actions naming convention in style guide

- .github/actions/should_run_monty/action.yml
- .github/workflows/docs.yml
- .github/workflows/tools.yml
This pull request improves the robustness of "should run" checks. As noted in #71, if there are two closely timed `push` events, the `git diff HEAD^1` will always diff against the latest commit instead of the one for which the check runs. Now, the check compares the desired commit against the previous one.
> ci: use commit sha instead of HEAD to check changes on push

- .github/actions/should_run_monty/action.yml
- .github/workflows/monty.yml
- .github/workflows/monty_api_docs.yml
When resuing the `should_run_monty` action, the context it is running in can change. For example, when triggered by a `workflow_run` event, there is no `github.sha` in context. This pull request makes all inputs explicit so that the action will work independently of context.
> ci: should_run_monty action explicit inputs

- .github/workflows/monty.yml
- .github/workflows/monty_api_docs.yml
After #73, I learned that the `actions/download-artifact@v4` cannot find an artifact uploaded with `actions/upload-pages-artifact@v3` (or at least I haven't found a way to configure it correctly).
This pull request uploads a "normal" Monty API Docs artifact via `actions/upload-artifact@v4`, so that `actions/download-artifact@v4` can find it. This "normal" artifact is then downloaded and the GitHub Pages artifact is created and uploaded in the Monty API Docs workflow and then deployed.
> ci: generate pages artifact in Monty API Docs workflow

- .github/workflows/monty_api_docs.yml
`github-token` is a required parameter for `actions/download-artifact@v4` to download an artifact from a different workflow run.
-- https://github.com/actions/download-artifact?tab=readme-ov-file#inputs
> ci: provide required github-token param

- src/tbp/monty/simulators/habitat/actuator.py
I noticed that not all [HabitatActuator](https://github.com/thousandbrainsproject/tbp.monty/blob/d5631219e86f1fbaa69a8b96dcacd118b023c493/src/tbp/monty/simulators/habitat/actuator.py#L49) symbols appear in the API documentation. This is because they were not exported as part of `__all__`. This pull request exports the symbols that are used as types.
> fix: export habitat actuator symbols that are used as types

- src/tbp/monty/frameworks/models/motor_policies.py
- tests/unit/policy_test.py
This pull request makes progress on decoupling Monty from HabitatSim (identified in #52). Specifically, the `habitat_sim` dependency within `motor_policies.py` is removed.
These temporary tests (excluded from the pull request) guided the changes in addition to the standard test suite. Notably, `Rotation` expects an `x, y, z, w` quaternion format.
```python
def test_hab_utils_quat_rotate_vector(self):
"""Verify hab_utils.quat_rotate_vector replacement results."""
quat_wxyz = qt.quaternion(1, 2, 3, 4)
vec_xyz = np.array([5, 6, 7])
hu_vec_rotated_xyz = hab_utils.quat_rotate_vector(quat_wxyz, vec_xyz)
print(hu_vec_rotated_xyz)  # [2.6 6.  8.2]
qt_vec_rotated_xyz = qt.rotate_vectors(quat_wxyz, vec_xyz)
print(qt_vec_rotated_xyz)  # [2.6 6.  8.2]
rot_vec_rotated_xyz = …
```
> refactor: remove habitat_sim dependency in motor_policies.py

- .github/workflows/monty_api_docs.yml
This pull request updates the Monty API Docs workflow to use the correct git SHA when looking for an artifact.
In the screenshot below, we can see that Should Run Monty API Docs is being triggered with the correct git SHA; however, the SHA in the artifact name is the latest on the main branch and not the desired one for the workflow.
-- https://github.com/thousandbrainsproject/tbp.monty/actions/runs/12060456960/job/33630906625
-- https://github.com/thousandbrainsproject/tbp.monty/actions/runs/12060216594
-- https://github.com/thousandbrainsproject/tbp.monty/actions/runs/12060409282
> ci: use git sha from workflow_run trigger and not latest commit

- .github/workflows/cla.yml
I am trying to understand why the CLA workflow fails to write comments on a pull request. This is an attempt to see if it requires `pull-request: write` permission despite using the Issues write endpoint.
> ci: grant pull-requests write to cla workflow

- docs/contributing/guides-for-maintainers/triage.md
This Pull Request documents an update to the **Maintainer** triage process.
We do not move forward with Pull Requests until the CLA signature is processed and the CLA check passes. **Maintainer**s are instructed to apply the `cla` label and skip triage until the CLA check passes. The change here updates the triage process to consist of two phases:
1. Review pull requests that are pending CLA
2. Triage pull requests with CLA check passing
Requesting all **Maintainer**s to review as this is a triage process change.
> docs: add cla label to faciliate pull request triage

- rfcs/0004_action_object/habitatenv_step_seq_diagram_desired.md
The [current Mermaid diagram preview in RFC 4](https://github.com/thousandbrainsproject/tbp.monty/blob/21954a3f97a9abe990734354b9a71b03f516c26a/rfcs/0004_action_object/habitatenv_step_seq_diagram_desired.md) does not render due to missing trailing whitespace.
This pull request adds trailing whitespace so that [the preview renders in GitHub](https://github.com/tristanls/tbp.monty/blob/f4fff071ab86ec1a07926c6e0f920eb69dc5800d/rfcs/0004_action_object/habitatenv_step_seq_diagram_desired.md).
> rfc: mermaid diagram trailing spaces required for preview to render

- src/tbp/monty/frameworks/models/motor_policies.py
when running
```shell
% python benchmarks/run.py -e randrot_noise_10distinctobj_surf_agent
% python benchmarks/run_parallel.py -e randrot_noise_10distinctobj_surf_agent
```
the following run-time errors can be observed:
```shell
.../tbp/monty/frameworks/models/motor_policies.py:1259: RuntimeWarning: divide by zero encountered in scalar divide
return -np.degrees(np.arctan(x / z))
.../numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
.../numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
ret = ret.dtype.type(ret / rcount)
```
as these might affect numeric results, an analysis is necessary. This has implications for published benchmarks that were affected.
[Initial …
> Fix division by zero when running the tutorial experiment

- docs/how-to-use-monty/getting-started.md
Our Anaconda installation instructions are incorrect for the latest versions, as reported in #81 and #95. This pull request updates the instructions, which no longer distinguish between Anaconda and Miniconda.
This pull request will resolve #95.
> docs: update Anaconda env create commands for latest version

- benchmarks/results/montymeetsworld.csv
- benchmarks/results/ycb_10objs.csv
- benchmarks/results/ycb_77objs.csv
- benchmarks/results/ycb_unsupervised.csv
- docs/overview/benchmark-experiments.md
This PR updates benchmark results tables after migrating to AWS. No changes have been made to tbp.monty's core code since the last set of complete benchmarks was completed.
> Update benchmark results after migrating to AWS.

- .github/workflows/cla.yml
I am pinning cla-assistant to [v1.0.0](https://github.com/thousandbrainsproject/cla-assistant/releases/tag/v1.0.0) to change cla-assistant code in https://github.com/thousandbrainsproject/cla-assistant/pull/4 without breaking existing workflows.
> ci: pin cla-assistant@v1.0.0

- .github/workflows/cla.yml
The CLA process was updated to store CLA signatories in a DynamoDB database in the scope of https://github.com/thousandbrainsproject/cla/pull/10.
This pull request updates the CLA workflow to use `cla-assistant@v2.0.0`, which checks the DynamoDB database for who signed the CLA.
The required `CLA_ASSISTANT_ACCESS_KEY_ID` and `CLA_ASSISTANT_SECRET_ACCESS_KEY` secrets are already configured for this repository.
> ci: use cla-assistant@v2.0.0

- .github/workflows/docs_preview.yml
Which is not what we want.  This happens as a default security feature when you're using `pull_request_target`.
> Tools: Docs Preview was Previewing the Main Branch

- docs/contributing/documentation.md
Update the docs' documentation page about how to install and use Vale.
> Docs: How to use Vale

- src/tbp/monty/frameworks/config_utils/cmd_parser.py
- src/tbp/monty/frameworks/run_parallel.py
- tests/unit/run_parallel_test.py
I noticed that when we run an experiment with `run_parallel` it outputs:
```
-------- Running evaluation experiment randrot_10distinctobj_surf_agent with 16 cpus --------
```
16 is the number of episodes that will run in parallel. However, this does not guarantee 1 CPU per episode as an episode may launch multi-CPU computations.
This pull request updates the output to read `with 16 episodes in parallel` and renames the `--num_cpus` option and `num_cpus` parameter to `--num_parallel` and `num_parallel` respectively.
As this is a breaking change, I request a broader review from recent experiment runners.
@hlee9212, this impacts floppy copies of run_parallel.
> refactor!: rename num_cpus to num_parallel for run_parallel

- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/environments/embodied_environment.py
- src/tbp/monty/frameworks/environments/habitat.py
- src/tbp/monty/frameworks/environments/real_robots.py
- src/tbp/monty/frameworks/environments/two_d_data.py
- src/tbp/monty/simulators/habitat/simulator.py
- tests/unit/embodied_data_test.py
This pull request removes Habitat dependency from `frameworks/environments/embodied_data.py` as part of the work to decouple Monty runtime from HabitatSim.
Previous planning called for writing a replacement `get_bounding_corners` function. However, after some investigation, it became clear that the use of `get_bounding_corners` within `embodied_data.py` is done only with the expectation that the Habitat environment is being used. As such, removing the dependency directly is a better refactor.
This refactoring moves the use of Habitat-specific `get_bounding_corners` into Habitat-specific `frameworks/environment/habitat.py`. To accomplish this, the `EmbodiedEnvironment` interface is expanded with `add_object` and `remove_all_objects` methods promoted directly from the `HabitatSim` …
> refactor: remove habitat dependency from embodied_data

- MAINTAINERS.md
As per discussion by the current maintainers, we have agreed to add @ramyamounir as a Maintainer to the TBP's governance https://thousandbrainsproject.readme.io/docs/governance#adding-maintainers
This decision was made in light of the large, well-written contribution he made to the codebase in summer 2024 while it was still closed-source (adding the EvidenceSDR to Monty), as well as the more recent contributions he has made.
> Add Ramy as maintainer

- .github/workflows/docs_preview.yml
Docs preview was running on all PR events, which meant it runs when the PR is merged or closed and this is not desired.
> Fix: Don't run docs preview when the PR is closed, or merged

- .github/workflows/cleanup_docs_preview.yml
TLDR; docs preview cleanup is now run on any closed PR and on any push to main, regardless of what changed, to ensure no dangling previews are left around.
When does this happen?
If you create a PR and there is a doc change, a docs preview is created. If you undo the change to the documentation and push that to the PR branch then close or merge the PR, the cleanup action is not activated as none of its paths have changed leading to a docs preview never been deleted.
> Fix: Dangling docs preview

- docs/future-work/cmp-hierarchy-improvements.md
- docs/future-work/environment-improvements.md
- docs/future-work/framework-improvements.md
- docs/future-work/learning-module-improvements.md
- docs/future-work/motor-system-improvements.md
- docs/future-work/oss-communication-improvements.md
- docs/future-work/sensor-module-improvements.md
- docs/future-work/voting-improvements.md
- docs/snippets/contributing-tasks.md
- tools/github_readme_sync/readme.py
- tools/github_readme_sync/tests/readme_test.py
This PR adds snippet functionality to the docs using the following format:
`!snippet[../snippets/repeating-text.md]`
`repeating-text.md` will be inserted before any other processing happens.
Example here: https://thousandbrainsproject.readme.io/v0.0-snippet-test/docs/osscommunication-improvements
> Docs: Snippets

- .github/workflows/docs_preview.yml
This PR fixes a problem where the docs are not getting rebuilt by the the preview system when the benchmarks/results change as they were not included in the build path trigger.
> Chore: Build the docs when benchmarks/results/** change

- benchmarks/results/ycb_unsupervised.csv
Thanks to @scottcanoe for catching this.
Table is fixed here: https://thousandbrainsproject.readme.io/v0.0-codeallthethingz-incorrect-unsupervised-csv-header/docs/benchmark-experiments#results-2
> Fix: incorrect header row in CSV for Unsupervised Benchmarks

- benchmarks/configs/monty_world_experiments.py
- benchmarks/configs/monty_world_habitat_experiments.py
- benchmarks/configs/pretraining_experiments.py
- benchmarks/configs/ycb_experiments.py
- src/tbp/monty/frameworks/experiments/monty_experiment.py
This PR removes the need to specify unused data loader classes and args in experiment configs.
Monty experiment configs currently require specifying both training and eval data loaders, regardless of whether both are needed. This means we end up with loads of lines like
```python
some_pretraining_config = dict(
.
.
.
eval_dataloader_class=ED.InformedEnvironmentDataLoader,  # just placeholder
eval_dataloader_args=get_env_dataloader_per_object_by_idx(start=0, stop=1),
)
```
or 
```python
some_eval_config = dict(
.
.
.
train_dataloader_class=ED.InformedEnvironmentDataLoader,
train_dataloader_args=get_env_dataloader_per_object_by_idx(start=0, stop=10),
)
```
This adds clutter and may also be misleading, especially to newcomers. This is a small PR that improves quality of life and allows us to …
> Dont require unused dataloaders

- .github/workflows/cleanup_docs_preview.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/docs_preview.yml
I noticed that [actions were executing and failing on my fork](https://github.com/tristanls/tbp.monty/actions). Adding missing conditional to only run in the `thousandbrains/tbp.monty` repo.
> ci: only run actions in thousandbrains tbp.monty repo

- rfcs/0000_monty_versioning.md
- rfcs/0007_monty_versioning.md
For easier reading, see the RFC on my fork: https://github.com/tristanls/tbp.monty/blob/rfc_monty_versioning/rfcs/0000_monty_versioning.md
> RFC 7 Monty Versioning

- src/tbp/monty/__init__.py
When testing building Monty for `conda` distribution, observed that `conda` does not allow `-` in the version name.
```
(tbp.monty) me@only_slightly_bent tbp.monty % conda build .
(...)
CondaBuildUserError: Bad character(s) (-) in package/version: 0.0.1-dev0.
```
This pull request resets the version to `0.0.0` to satisfy this `conda` constraint. According to [RFC 7 Monty Versioning](https://github.com/thousandbrainsproject/tbp.monty/blob/main/rfcs/0007_monty_versioning.md), we also do not anticipate using build versions at this time.
> build: reset version to 0.0.0 to satisfy conda constraint

- src/tbp/monty/frameworks/models/evidence_matching.py
@vkakerbeck gave this explanation for `evidence_update_threshold` in a video. This explanation is what clicked for me and apparently @scottcanoe. This pull request adds it for context for others who try to understand the purpose of this parameter.
> docs: additional context for evidence_update_threshold

- .github/actions/version_updated/action.yml
I forgot to use `working-directory` in the `version_updated` action, [resulting in job failures](https://github.com/thousandbrainsproject/tbp.monty/actions/runs/13572685337/job/37941404176#step:3:142).
> build: set correct working-directory for version_updated action

- .github/workflows/monty_publish.yml
The `version_updated` action executes the comparison:
```
git diff --name-only 9f59ad0105d877a40f7d058da3f88cc43c4c7ce0^1 > changed_files.txt
```
The `^1` at the end of the commit hash means to `diff` with the previous commit. However, the default checkout action uses `fetch-depth: 1`, which will not include the previous commit.
```
Run actions/checkout@v4
with:
path: tbp.monty
repository: thousandbrainsproject/tbp.monty
token: ***
ssh-strict: true
ssh-user: git
persist-credentials: true
clean: true
sparse-checkout-cone-mode: true
fetch-depth: 1
fetch-tags: false
show-progress: true
lfs: false
submodules: false
set-safe-directory: true
...
Checking out the ref
/usr/bin/git log -1 --format=%H
9f59ad0105d877a40f7d058da3f88cc43c4c7ce0
```
Results in the error:
```
git diff --name-only …
```
> build: need fetch-depth=2 for git diff commit^1 comparison

- src/tbp/monty/__init__.py
This is a test version bump to exercise Monty Publish workflow fully executing on version change.
The workflow already triggers and does not proceed when the version is not updated, e.g., https://github.com/thousandbrainsproject/tbp.monty/actions/runs/13575067493/job/37949221067
> chore: version 0.0.1

- .github/workflows/monty_publish.yml
Upload errors with `('Authorization token is no longer valid', 401)`. Maybe it is the explicit `::add-mask::` GitHub directive messing things up. Removing it to test.
I'll monitor and rotate the token immediately if we leak it this way.
> build: remove explicit mask that maybe causes 401

- .github/workflows/monty_publish.yml
Because I'm capturing the output path before setting target platform in the configuration, the output does not correspond to the actual target platform and nothing is found when trying to upload. In `osx` case, platform is `osx-arm64` but builds for `osx-64` and things don't line up.
This pull request ensures configuration is present before we read the output path.
This should get `osx-64` upload to work.
> build: set target platform before capturing (platform-dependent) path

- .github/actions/version_updated/action.yml
- .github/actions/version_updated/check_version_updated.sh
- .github/workflows/monty_publish.yml
This pull request introduces a `tag_version_monty_publish` job to the Monty Publish workflow.
The job is only triggered when Monty workflow on the `main` branch succeeds, which is after a commit is merged to `main`.
```yml
tag_version_monty_publish:
name: tag-version-monty-publish
if: ${{ github.event.workflow_run.conclusion == 'success' }}
...
```
The version is tagged only when that commit contains a version change in `src/tbp/monty/__init__.py`.
```yml
...
- name: Tag version
if: ${{ steps.version_updated.outputs.version_updated == 'true' }}
working-directory: tbp.monty
run: |
git tag v${{ steps.version_updated.outputs.version }}
git push origin v${{ steps.version_updated.outputs.version }}
```
The Version updated action now additionally returns `version` from …
> build: tag version commit with version tag

- environment.yml
- environment_arm64.yml
- pyproject.toml
- recipe/meta.yaml
In our current setup, we use two package managers to satisfy Monty dependencies: `conda` and `pip`. This was fine when we were not distributing Monty. However, to publish and distribute Monty, we need to pick a single source for our dependencies. Today, this needs to be `conda` as not all dependencies are available on `pip` (e.g., `habitat_sim`).
By using `conda` to source all dependencies, when we publish `thousandbrainsproject::tbp.monty`, we can specify dependencies that should be installed when someone installs `thousandbrainsproject::tbp.monty`. If we do not do this, there is no standard install method for Monty on either `conda` or `pip`. (Without a standard install method, we would be asking users to execute a custom sequence of steps; not impossible, but not as accessible as …
> build: source dependencies from conda

- src/tbp/monty/__init__.py
Publish recent changes and test the latest builds.
Only `build:`, one `refactor:`, and one `docs:` changes since `0.0.1`. As this is a backward-compatible change without any new features, the patch version is incremented.
> chore: version 0.0.2

- environment.yml
- environment_arm64.yml
- recipe/meta.yaml
When testing `thousandbrainsproject::tbp.monty==0.0.2`, it is possible to install a `numpy>1.23.5`. However, `numpy` versions `>=1.24` are missing `np.long` used by the code. This pull request pins `numpy<=1.23.5` to prevent `np.long` missing errors.
Example failure:
```
/home/me/.conda/envs/monty_lab/lib/python3.8/site-packages/numba/core/types/__init__.py:108: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
long_ = _make_signed(np.long)
Traceback (most recent call last):
File "dmc/run_parallel.py", line 16, in <module>
from configs import CONFIGS  # noqa: E402
File "/home/me/tbp/monty_lab/dmc/configs/__init__.py", line 1, in <module>
from .fig3_robust_sensorimotor_inference import CONFIGS as FIG_3_CONFIGS
File …
```
> build: pin numpy version, later ones are missing np.long

- src/tbp/monty/__init__.py
Patch version to release tbp.monty with pinned numpy dependency from https://github.com/thousandbrainsproject/tbp.monty/commit/81c61738ab83ba5a7ae2da7c3604f6deac775f32.
> chore: version 0.0.3

- docs/overview/faq-thousand-brains-project.md
- docs/overview/glossary.md
- tools/github_readme_sync/md.py
- tools/github_readme_sync/readme.py
- tools/github_readme_sync/tests/md_test.py
- tools/github_readme_sync/tests/readme_test.py
This PR fixes a bug where the description was not updating from the frontmatter in the document pages.
This was two fold
1. Because in readme.io it is called except, not description.
1. The description was not being read in from the document's frontmatter.
A term in the glossary page was also corrected to move to the right location and become a heading.
> chore: fix for bug where glossary has old description

- src/tbp/monty/frameworks/models/evidence_matching.py
- src/tbp/monty/frameworks/models/object_model.py
This is a 1 line PR to remove unnecessary initialization of possible locations in `EvidenceGraphLM`.
We should not need to set the `self.possible_locations` using `self.graph_memory.get_initial_hypotheses` in the `EvidenceGraphLM.reset` [function](https://github.com/thousandbrainsproject/tbp.monty/blob/e62e1bca981f7ef3a4e2832e11f80056ce189981/src/tbp/monty/frameworks/models/evidence_matching.py#L366). Whatever we set here at reset will be overwritten later in `_update_evidence` initialization of hypothesis space [here](https://github.com/thousandbrainsproject/tbp.monty/blob/e62e1bca981f7ef3a4e2832e11f80056ce189981/src/tbp/monty/frameworks/models/evidence_matching.py#L987).
It's not a big thing, but it causes `self.possible_locations` and `self.possible_poses` to be out of sync (i.e., …
> refactor: Avoid possible locations double initialization.

- src/tbp/monty/frameworks/experiments/profile.py
- tests/unit/profile_experiment_mixin_test.py
While working on https://github.com/thousandbrainsproject/tbp.monty/pull/220, we realized that this mixin might be affected by the changes there. Upon investigation, I noticed that it was lacking any tests to make sure at a bare minimum that it works, so I'm adding some here.
I also added an `__init_subclass__` method to it to check and ensure the required invariants are true when it is used.
> chore: add tests for ProfileExperimentMixin

- docs/how-to-use-monty/getting-started.md
I noticed it is easy to get a broken experience installing `tbp.monty` on Apple Silicon if I don't have Rosetta installed.
This pull request updates install instructions to avoid the cryptic `Bad CPU type in executable` error when creating the conda `tbp.monty` environment.
> docs: install rosetta on apple silicon instructions

- src/tbp/monty/frameworks/experiments/monty_experiment.py
- src/tbp/monty/frameworks/experiments/pretraining_experiments.py
- src/tbp/monty/frameworks/run.py
- src/tbp/monty/frameworks/run_parallel.py
- tests/unit/base_config_test.py
- tests/unit/evidence_lm_test.py
- tests/unit/graph_building_test.py
- tests/unit/graph_learning_test.py
- tests/unit/policy_test.py
- tests/unit/profile_experiment_mixin_test.py
- tests/unit/run_parallel_test.py
- tests/unit/sensor_module_test.py
This is the second phase of [the work I proposed on Discourse][forum] to make MontyExperiment into a context manager.
This moves the config setup into a constructor for the class, leaving the part that initializes the model and datasets in the `setup_experiment` method. Then we call the simplified setup method in the context manager `__enter__` method.
The rest of this is updating the call sites to use the new context manager style more completely.
[forum]: https://thousandbrains.discourse.group/t/investigation-into-linux-test-failures-and-possible-improvements/468
> refactor!: MontyExperiment context manager part 2

- src/tbp/monty/__init__.py
Minor version release due to Major version 0 and a breaking change refactoring MontyExperiment context manager.
> chore: version 0.2.0

- src/tbp/monty/frameworks/models/displacement_matching.py
- src/tbp/monty/frameworks/models/graph_matching.py
- tests/unit/evidence_sdr_lm_test.py
This change refactors the logic of detecting the first movement since the reset signal from `GraphLM.matching_step` to `GraphLM._agent_moved_since_reset`. This will allow us to overwrite this logic in other PRs (e.g., [PR#221](https://github.com/thousandbrainsproject/tbp.monty/pull/221#discussion_r2021342279)) without modifying the `matching_step` function.
Additionally, `not_moved` has been renamed to `first_movement_detected` to avoid the slightly confusing double negatives in cases such as `not_moved = False`.
This change required other changes in `DisplacementGraphLM` and `EvidenceSDRIntegrationTest`.
I ran the benchmark experiments for `randrot_noise_10distinctobj_surf_agent` and `randrot_noise_10distinctobj_dist_agent` for a quick sanity check; they gave the same results as before …
> refactor: first movement logic in GraphLM

- pyproject.toml
- src/tbp/monty/frameworks/models/motor_policies.py
- src/tbp/monty/frameworks/utils/transform_utils.py
- src/tbp/monty/simulators/tacto/__init__.py
As of ruff 0.8.0, `ANN101` and `ANN102` have been removed (https://astral.sh/blog/ruff-v0.8.0), and depreciated since version 0.2.0. This PR updates the ruff version from 0.7.1 to 0.11.4, which is the latest version as of 2025/04/04. I have specified the version for reproducibility (removing the version pins will use the latest version of each tool).
> chore: updating ruff version and removing ANN101 and ANN102 from ignore

- pyproject.toml
I wrote a short script to loop through the ignore list under [tool.ruff.lint] and remove those that pass. 
Core logic of script for reference:
```python
def extract_ignore_rules(pyproject_path: Path) -> List[str]:
"""Extract the ruff ignore rules from pyproject.toml."""
with open(pyproject_path, "rb") as f:
data = tomli.load(f)
ignore_rules = data["tool"]["ruff"]["lint"]["ignore"]
return ignore_rules
def check_rule(rule: str, src_dirs: List[str], tbp_monty_dir: Path) -> bool:
"""
Check if a rule produces any errors when run with ruff check.
Returns True if no errors are found (rule can be removed).
"""
cmd = ["ruff", "check"] + src_dirs + ["--select", rule]
try:
result = subprocess.run(
cmd,
cwd=tbp_monty_dir,
stdout=subprocess.PIPE,
stderr=subprocess.PIPE,
text=True,
check=False,
) …
```
> chore: clean up ruff's ignore list to remove rules that pass

- src/tbp/monty/frameworks/models/motor_policies.py
While this is marked as a breaking change (removing a method from the API), there are no subclass implementations of this abstract method, meaning that if it were ever called, it would have thrown an error. Since we observe no such errors, there are no calls of this method in the code, and there's a `TODO` questioning needing the method, this method is now removed.
> refactor!: remove unused MotorSystem.update method

- src/tbp/monty/frameworks/models/monty_base.py
The `MotorSystem` `step_type` attribute is unused but is set as part of `MontyBase` methods (and incorrectly). This pull request removes setting the unused attribute.
> refactor!: remove setting unused MotorSystem.step_type attribute

- .github/workflows/tools.yml
- tools/generate_api_docs/__init__.py
- tools/generate_api_docs/source/__init__.py
- tools/generate_api_docs/source/conf.py
- tools/github_readme_sync/cli.py
- tools/github_readme_sync/file.py
- tools/github_readme_sync/hierarchy.py
- tools/github_readme_sync/readme.py
- tools/github_readme_sync/req.py
- tools/github_readme_sync/tests/export_test.py
- tools/github_readme_sync/tests/file_test.py
- tools/github_readme_sync/tests/hierarchy_test.py
- tools/github_readme_sync/tests/req_test.py
- tools/github_readme_sync/upload.py
Tools workflow does not run when `pyproject.toml` changes, so if linting or other tooling configuration changes (for example: https://github.com/thousandbrainsproject/tbp.monty/pull/233), it won't be noticed until something alters the tools.
This pull request ensures tools checks run when `pyproject.toml` changes.
The newly effective linter rules are addressed for checks to pass in `tools`.
> chore: run tools workflows when pyproject.toml changes

- src/tbp/monty/frameworks/models/evidence_matching.py
This pull request ensures that `_add_detailed_stats` override does not add new parameters by brining `get_rotations` determination into `_add_detailed_stats`.
This will resolve an issue of an unused method argument in `NoResetEvidenceGraphLM._add_detailed_stats` override: https://github.com/thousandbrainsproject/tbp.monty/pull/227#discussion_r2036072556.
> refactor: do not add extra params to _add_detailed_stats override

- benchmarks/configs/pretraining_experiments.py
- benchmarks/make_detailed_follow_up_configs.py
- docs/how-to-use-monty/tutorials/multiple-learning-modules.md
- src/tbp/monty/frameworks/config_utils/config_args.py
- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/experiments/data_collection_experiments.py
- src/tbp/monty/frameworks/experiments/monty_experiment.py
- src/tbp/monty/frameworks/experiments/object_recognition_experiments.py
- src/tbp/monty/frameworks/loggers/graph_matching_loggers.py
- src/tbp/monty/frameworks/models/evidence_matching.py
- src/tbp/monty/frameworks/models/graph_matching.py
- src/tbp/monty/frameworks/models/monty_base.py
- src/tbp/monty/frameworks/models/motor_policies.py
- src/tbp/monty/frameworks/models/motor_system.py
- src/tbp/monty/frameworks/utils/follow_up_configs.py
- tests/unit/embodied_data_test.py
- tests/unit/evidence_lm_test.py
- tests/unit/graph_learning_test.py
- tests/unit/habitat_data_test.py
- tests/unit/policy_test.py
This pull request removes motor policies from the `MotorSystem` inheritance hierarchy. 
This is a breaking change (`refactor!:`) due to configuration changes. The functionality, once configuration is updated, works the same.
A new inheritance hierarchy is introduced with `MotorPolicy` replacing `MotorSystem` at the top. The rest of the policy hierarchy remains intact.
Going forward, motor policies are an attribute of `MotorSystem` instances, specifically: `motor_system._policy`.
`MotorSystem` configuration changes as follows:
- `motor_system_class` is always now an instance of `MotorSystem`
- `motor_system_args` is now a dictionary `{"policy_class":..., "policy_args":...}` where `policy_args` contain what used to be in `motor_system_args`, i.e., the policy configuration.
For example: …
> refactor!: motor policies are an attribute of MotorSystem

- tools/generate_api_docs/source/conf.py
- tools/github_readme_sync/cli.py
Follow on to #237, where I incorrectly add `Path` objects to `sys.path` instead of strings.
> A program is free to modify this list for its own purposes. **Only strings and bytes** should be added to [sys.path](https://docs.python.org/3.8/library/sys.html#sys.path); all other data types are ignored during import.
> -- https://docs.python.org/3.8/library/sys.html#sys.path
> chore: only strings should be added to sys.path

- src/tbp/monty/frameworks/environments/two_d_data.py
- src/tbp/monty/frameworks/experiments/pretraining_experiments.py
- src/tbp/monty/frameworks/models/sensor_modules.py
As I was writing the Monty for custom applications tutorial, I noticed that the Omniglot environment was not working properly anymore. This is largely due to the fact that we don't have unit tests for it, so previous changes that broke it were unnoticed. These fixes make it work as intended again. Followup work would include actually testing it, however I think it is a bit more involved since we don't want to have to download the dataset for the unit tests (maybe there is an easy solution I am not aware of).
> fix: Fix Omniglot Environment

- tools/plot/README.md
- tools/plot/__init__.py
- tools/plot/cli.py
- tools/plot/objects_evidence_over_time.py
- tools/plot/pose_error_over_time.py
- tools/plot/tests/__init__.py
- tools/plot/tests/objects_evidence_over_time.py
- tools/plot/tests/pose_error_over_time_test.py
This is an initial implementation of a plot tool. It supports plotting figures proposed in #227.
```
(tbp.monty) tslominski@Overlords-MacBook-Pro tbp.monty % python -m tools.plot.cli -h                                     
usage: cli.py [-h] [--debug] {objects_evidence_over_time,pose_error_over_time} ...
Plot a figure
positional arguments:
{objects_evidence_over_time,pose_error_over_time}
objects_evidence_over_time
Plot evidence scores for each object over time.
pose_error_over_time
Plot MLH pose error and theoretical limits over time.
optional arguments:
-h, --help            show this help message and exit
--debug               Enable debug logging
```
When we added new plots in https://github.com/thousandbrainsproject/tbp.monty/pull/227, I noticed how different that code is from …
> chore: initial implementation of plot tool

- src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
- tests/unit/frameworks/models/mixins/__init__.py
- tests/unit/frameworks/models/mixins/no_reset_evidence_test.py
This pull request enforces `TheoreticalLimitLMLoggingMixin` compatibility via code instead of convention.
> refactor: enforce TheoreticalLimitLMLoggingMixin compatibility requirement

- src/tbp/monty/frameworks/environments/embodied_data.py
This pull request reduces the number of interactions between DataLoader and MotorSystem policies regarding policy `state`. This slightly reduces the complexity in a few places for follow-on refactoring.
There are two types of changes:
First, capture the state from the dataset in a local `state` variable, interact with it, and then set `motor_system._policy.state` once. This ends up looking as follows:
```python
self._observation, state = self.dataset.reset()
self.motor_system._policy.state = state
```
Second, don't set observations or state when they will be immediately overridden. This ends up looking as follows:
```python
_, _ = self.dataset[set_agent_pose]
self._observation, self.motor_system._policy.state = self.dataset[
set_sensor_rotation
]
```
> refactor: reduce dataloader and motor system policy state interactions

- src/tbp/monty/frameworks/models/monty_base.py
We probably never noticed this because `MontyForGraphMatching(MontyBase)` overrides this method with its own implementation. Within that override, you'll notice the correct usage of `getattr`:
```python
lm_step_method = getattr(self.learning_modules[i], self.step_type)
assert callable(lm_step_method), f"{lm_step_method} must be callable"
lm_step_method(sensory_inputs)
```
> fix: MontyBase._step_learning_modules now works

- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/monty_base.py
- src/tbp/monty/frameworks/models/motor_policies.py
- src/tbp/monty/frameworks/models/motor_system.py
- src/tbp/monty/frameworks/models/motor_system_state.py
- tests/unit/frameworks/models/motor_policies_test.py
- tests/unit/policy_test.py
In a previous refactor (#234), I separated the `MotorSystem` from `MotorPolicy` and set things up so that a policy was a `motor_system._policy` attribute. However, the motor system state remained attached to the motor policy.
Since we want to be able to swap motor policies, we want to maintain the motor system state outside of the motor policy.
This pull request consolidates motor system state to be a `MotorSystem._state` property. Additionally, since motor policies no longer track motor system state, all motor policy code is passed the motor state explicitly via a `state: Optional[MotorSystemState]` argument.
One consequence of this is in dataloaders (`embodied_data.py`). We see two directly invoked policy methods being passed the motor system state explicitly, for example:
```python …
```
> refactor!: state is stored in motor system instead of policies

- src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
- tests/unit/evidence_lm_test.py
- tests/unit/feature_flags.py
- tests/unit/graph_building_test.py
- tests/unit/graph_learning_test.py
- tests/unit/no_reset_evidence_lm_test.py
- tests/unit/policy_test.py
- tests/unit/run_parallel_test.py
- tests/unit/sensor_module_test.py
fyi @scottcanoe @hlee9212 @ramyamounir 
> [!NOTE]
> When reviewing, I highly recommend the "hide whitespace" view option for looking through the test changes
> <img width="438" alt="Screenshot 2025-04-23 at 14 45 40" src="https://github.com/user-attachments/assets/b66087ca-8b6f-47fa-afb1-5627d70f3b8b" />
This pull request extracts the `GetGoodView` positioning procedure (as a policy) from the `InformedEnvironmentDataLoader`. 
Note that this PR _only_ extracts the positioning procedure as a policy. It does not separate positioning procedures from policies. This is future work. This requires that `GetGoodView` take in unused arguments on initialization and invoke its `positioning_call` method. This awkwardness will be removed when positioning procedures are made distinct from policies.
This …
> refactor!: GetGoodView positioning procedure

- .git-blame-ignore-revs
Adding commit 47ad330d0573582e2f807770d1b4e59be0ca67d7 where we reformatted using `ruff format` to the list of commits to ignore in git-blame history.
To have local git use this, run the following:
```shell
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
> chore: ignore reformatting in git-blame

- tests/unit/graph_learning_test.py
- tests/unit/resources/unit_test_utils.py
This test currently fails on Linux machines (including in GH actions when run on a GPU instance) for unknown reasons, so we're trying to change the test to use faked observations instead of observations from HabitatSim.
Fixes #117
> test: refactor 5LM test to use fake observations

- .github/workflows/monty.yml
Newer versions of HabitatSim seem to require an actual GPU based on the errors we've seen trying to run without it, so we're switching the tests to run on a GPU instance.
> test: use GPU runner for monty tests

- src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
This pull request corrects the GetGoodView positioning procedure to operate exactly like the data loader's current `get_good_view()` code.
Here are a few `run_parallel.py` benchmarks from my laptop with old and new code paths. They are for comparison with https://github.com/thousandbrainsproject/tbp.monty/pull/275#issuecomment-2828993390, which had some discrepancies. I now observe no discrepancies.
| GetGoodView | Experiment | Correct (%) | Used MLH (%) | Num Match Steps | Rotation Error | WandB |
|---|---|---|---|---|---|---|
| old | base_config_10distinctobj_dist_agent | 99.28571428571428 | 0 | 35.49285714285714 | 0.30008273381294964 | [run](https://wandb.ai/thousand-brains-project/Monty/runs/l3isif50/overview)
| new | base_config_10distinctobj_dist_agent | 99.28571428571428 | 0 | …
> fix: GetGoodView positioning procedure matches previous code

- .github/workflows/monty_publish.yml
The Monty Publish workflow fails after its default Python version apparently changed to 3.13. 
```
conda install anaconda-client conda-build
...
Channels:
- defaults
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | done
Solving environment: - \ | / - \ | failed
LibMambaUnsatisfiableError: Encountered problems while solving:
- package conda-build-3.0.22-py27h62b9468_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
Could not solve for environment specs
The following packages are incompatible
├─ conda-build =* * is installable with the potential options
│  ├─ conda-build [24.1.0|24.1.1|...|3.28.4] would require
│  │  └─ python >=3.10,<3.11.0a0 *, which can be installed;
│  ├─ conda-build [24.1.0|24.1.1|...|3.28.4] would require
│  │ …
```
> ci: pin python version for monty_publish workflow

- rfcs/0010_conventional_commits.md
This pull request updates RFC 10 examples to resemble pull request commit messages used in Monty more closely. Previously, the `<description>` section in examples did not include the pull request number. Examples now contain the pull request number, as they are expected to be part of the `<description>`.
> rfc: update RFC 10 examples to include PR number

- .gitignore
I use [direnv](https://direnv.net/) file for defining directory-specific environment variables (e.g., WANDB_DIR) that are only available inside the `tbp.monty` directory, as well as automatically activate and deactivate the conda environment when I `cd` in and out of the `tbp.monty` directory. It's helpful to gitignore the associated dot file `.envrc`.
> chore: ignore .envrc files for direnv

- src/tbp/monty/frameworks/experiments/monty_experiment.py
Currently, there is no case where a model is not an instance of `MontyBase`. This pull request removes the else branch that will never be executed.
> refactor: remove unused else case

- src/tbp/monty/frameworks/environments/embodied_data.py
I forgot to remove this when implementing action objects. This pull request removes the initialization of this unused property.
> refactor: remove unused _amount prop forgotten during RFC 4 refactor

- benchmarks/results/ycb_10objs.csv
- benchmarks/results/ycb_77objs.csv
- benchmarks/results/ycb_unsupervised.csv
- benchmarks/results/ycb_unsupervised_inference.csv
- docs/overview/benchmark-experiments.md
- pyproject.toml
- src/tbp/monty/frameworks/environments/embodied_data.py
- tests/unit/policy_test.py
This pull request is best illustrated by showing the trace of actions and their processing results in the `test_surface_policy_moves_back_to_object` test.
Before showing the traces, a quick high-level review of SurfacePolicy's `touch_object` and `dynamic_call`.
The `touch_object` essentially tries to find the object as follows:
- try `OrientHorizontal` repeatedly for up to 360 degrees
- try `OrientVertical` repeatedly for up to 360 degrees (total of 720, it keeps count)
- try random direction
- once object visible, `MoveForward` and success!
The `dynamic_call` is a cycle with three motor-only steps and one where we pass sensor data to the learning module:
- `MoveForward` (motor-only)
- `OrientHorizontal` (motor-only)
- `OrientVertical` (pass to LM)
- `MoveTangentially` (motor-only)
The …
> fix: motor_only_step flag is now always True for motor-only steps

- src/tbp/monty/frameworks/models/evidence_matching.py
- src/tbp/monty/frameworks/utils/evidence_matching.py
- tests/unit/frameworks/utils/evidence_matching_test.py
Based on some discussions with @nielsleadholm [here](https://github.com/thousandbrainsproject/tbp.monty/pull/289#discussion_r2074348453), we agreed to separate out the restructuring of `_update_evidence` in `EvidenceGraphLM` from the resampling logic.
This PR aims to refactor and simplify the `_update_evidence` function. The functionality remains the same but much of the logic has been refactored into other functions (e.g., `_displace_hypotheses`). Some of the refactoring aims to make the functions self-contained. For example instead of passing the range of indices in the hypothesis space and letting the function directly modify the hypothesis space (class variables), I pass the actual hypotheses and return the modified ones. This way these functions can be easily reused, unit-tested, …
> refactor: restructuring of _update_evidence

- benchmarks/results/ycb_10objs.csv
- benchmarks/results/ycb_77objs.csv
- benchmarks/results/ycb_unsupervised.csv
- benchmarks/results/ycb_unsupervised_inference.csv
- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
- tests/unit/policy_test.py
This pull request removes the interference between SurfacePolicy's `dynamic_call` implementation and its embedded `touch_object` positioning procedure, which finds the object if the sensor loses it. Additionally, it resets the `touch_object` state between each object finding attempt. Previously, the `touch_object` procedure would resume from the random state it ended in from the previous attempt to find the object.
The `touch_object` state reset is done by having the data loader reset the `touch_object` positioning procedure on success. This is not great, but for now, `touch_object` might have succeeded and not know it. In the future, when it is refactored to the `TouchObject` positioning procedure, the reset will be contained within the positioning procedure itself.
The interference is …
> fix: SurfacePolicy touch_object and dynamic_call no longer interfere

- src/tbp/monty/frameworks/run.py
We used to do this, but it seems like it's no longer done. I'm not sure why it was removed, but I found it useful to have a pprinted version of the experiment config in the logs. I'm happy to be convinced otherwise if this was removed for a specific reason.
Also not sure if chore is the correct label since it technically changes the output of an experiment but didn't feel like it was significant enough for feat.
> chore: print config by default

- .github/actions/should_run_monty/check_changed_files.sh
- .rsyncignore
This pull request adds `.rsyncignore` to help with infrastructure tooling when using `rsync`.
> chore: add .rsyncignore to help with infra tooling

- benchmarks/results/ycb_10objs.csv
- benchmarks/results/ycb_77objs.csv
When working on other pull requests, I noticed that the documented benchmark values no longer reflect the `main` branch code benchmarks. It appears that the reason for the discrepancy is the use of _2-decimal point rounded_ radian values when converting from radians to degrees for the initial benchmark CSV (see below for details).
This pull request updates the benchmarks as of commit 451ba5f576cfdf3eb1b14250d85125429b93d1e4 (the HEAD of `main` branch as of the writing of this pull request).
I rearranged the diff below for easier reading:
`benchmarks/results/ycb_10objs.csv`
```diff
-base_config_10distinctobj_dist_agent,100.00,0.00,37,16.04,5,19
+base_config_10distinctobj_dist_agent,100.00,0.00,37,16.20,2,8
base_config_10distinctobj_surf_agent,100.00,0.00,28,11.62,2,10 …
```
> docs: benchmark updates for current code

- benchmarks/results/ycb_10objs.csv
- benchmarks/results/ycb_77objs.csv
- benchmarks/results/ycb_unsupervised.csv
- benchmarks/results/ycb_unsupervised_inference.csv
- src/tbp/monty/frameworks/models/motor_policies.py
- tests/unit/policy_test.py
The intended future refactor of `SurfacePolicy` is to separate the `TouchObject` positioning procedure. This was initially attempted in #306. However, after analysis, it turned out that #306 contained three algorithmic changes, and it was difficult to identify and accept the changes.
This pull request isolates and applies only one of the algorithmic changes: TouchObject positioning procedure now always ends with a MoveForward action.
This pull request ensures that the current embedded touch object positioning procedure (in the form of `touch_object` method) always runs until the viewfinder sees the object within range. Then, it executes the MoveForward action. The reason for implementing this change is that once the TouchObject positioning procedure is extracted in the future, it will …
> refactor!: SurfacePolicy touch_object phase always ends with MoveForward action

- benchmarks/results/ycb_10objs.csv
- src/tbp/monty/frameworks/environments/embodied_data.py
- tests/unit/embodied_data_test.py
- tests/unit/evidence_lm_test.py
- tests/unit/habitat_data_test.py
This turned out to be more complicated than I expected.
This pull request removes an extraneous reset coded in `__iter__` and ensures all data loaders do the reset logic inside `pre_episode` instead.
Since the reset logic now always happens in `pre_episode`, two previous tests that were testing for logging `patch_off_object` now throw a `ValueError`, since the experiment is being initialized off the object. If those original tests intended to ensure that we know that an experiment started off object, the new tests maintain that intent. However, if those original tests intended to test `patch_off_object` logging functionality specifically, we'll need a different test. Based on the original docstrings, I believe the intent was the former.
The three Habitat tests and two embodied data tests …
> refactor!: remove extraneous reset by refactoring reset out of __iter__

- pyproject.toml
We still ignore errors for now, but if you want local `mypy` type checking and set `ignore_errors=false`, then this `mypy` configuration will now correctly load available Monty code for type checking.
> chore: mypy configuration to recognize tbp.monty package

- .github/workflows/monty.yml
- uv.lock
As we move forward and add the MuJoCo simulator, we need to ensure we
are running the tests for the `uv` environment in GitHub Actions.
This adds a simple job to do it. Later we will want to have
the `check_*` jobs run using `uv` instead of Conda.
> test: add workflow for uv environment

- docs/how-to-use-monty/tutorials/multiple-learning-modules.md
- docs/how-to-use-monty/tutorials/running-inference-with-a-pretrained-model.md
- docs/how-to-use-monty/tutorials/unsupervised-continual-learning.md
Updating tutorials to reduce the likelihood of [people running into the missing imports problem](https://thousandbrains.discourse.group/t/missing-imports-in-tutorials-leads-to-name-myexperiments-is-not-defined-error).
Also, some tutorials had these and others didn't, so this update makes the tutorials consistent.
> docs: include asdict and MyExperiments imports in all tutorials

- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
This pull request partially implements #339. It moves `SurfacePolicy.get_depth_at_center` to `PositioningProcedure.depth_at_center`. 
The goal of having this pull request separate is to isolate and merge changes that do not alter benchmarks, while working towards identifying the most minor possible change responsible for benchmark changes in #339.
Observations are typed as `Any` to avoid introducing additional types and changes resulting from those.
> [!NOTE]
> This pull request resulted in no changes to benchmark numbers.
> refactor!: move get_depth_at_center to PositioningProcedure

- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
This pull request partially implements https://github.com/thousandbrainsproject/tbp.monty/pull/339. It raises `ObjectNotVisible` instead of returning a `None` action when `SurfacePolicy` finds itself off object.
The goal of having this pull request separate is to isolate and merge changes that do not alter benchmarks, while working towards identifying the most minor possible change responsible for benchmark changes in https://github.com/thousandbrainsproject/tbp.monty/pull/339.
> [!NOTE]
> This pull request resulted in no changes to benchmark numbers.
> refactor!: raise ObjectNotVisible instead of returning None action

- src/tbp/monty/frameworks/environments/embodied_data.py
- src/tbp/monty/frameworks/models/motor_policies.py
This pull request partially implements https://github.com/thousandbrainsproject/tbp.monty/pull/339. It only increments data loader `_counter` when on object, as `_counter` won't get incremented inside TouchObject positioning procedure.
The goal of having this pull request separate is to isolate and merge changes that do not alter benchmarks, while working towards identifying the most minor possible change responsible for benchmark changes in https://github.com/thousandbrainsproject/tbp.monty/pull/339.
> [!NOTE]
> This pull request resulted in no changes to benchmark numbers.
> refactor: only increment dataloader _counter when on object

- tools/plot/cli.py
- tools/plot/correct_percentage_per_episode.py
- tools/plot/objects_evidence_over_time.py
- tools/plot/pose_error_over_time.py
- tools/plot/tests/correct_percentage_per_episode.py
This PR adds a simple script to the plot tool under the name `correct_percentage_per_episode`. It will plot a bar chart with the percentage of correct steps on the y-axis and the episode target on the x-axis. The idea was suggested by @nielsleadholm and it would be a nice metric to report as part of the unsupervised inference experiments.
```zsh
usage: cli.py correct_percentage_per_episode [-h] [--debug] [-lm LEARNING_MODULE] [-t {primary,stepwise}] experiment_log_dir
positional arguments:
experiment_log_dir    The directory containing the experiment log with the detailed stats file.
optional arguments:
-h, --help            show this help message and exit
--debug               Enable debug logging
-lm LEARNING_MODULE, --learning_module LEARNING_MODULE
The name of the learning module …
```
> chore: add correct percentage figure to plot tool

- src/tbp/monty/__init__.py
Minor version release due to Major version 0 and breaking changes since 0.7.0.
- `EvidenceGraphLM` constructor parameter renamed from `evidence_update_threshold` to `evidence_threshold_config`.
- `InvalidEvidenceUpdateThreshold` error was moved and renamed to `InvalidEvidenceThresholdConfig`.
Using `logging` directly is no longer supported.
The updated Python logger usage is now to get the logger by module name at the top of the module:
```python
from tbp.monty.frameworks.models.object_model import GraphObjectModel
logger = logging.getLogger(__name__)
class MontyForGraphMatching(MontyBase):
"""General Monty model for recognizing object using graphs."""
```
Additionally, Python loggers are now initialized before the Monty model so that logging during initialization of the Monty model …
> chore: version 0.8.0

- .vale/styles/config/vocabularies/TBP/accept.txt
- docs/how-to-use-monty/tutorials/running-your-first-experiment.md
The first tutorial broke due to recent refactoring of the sensor- and learning-module hierarchy.
The original tutorial used the most general classes possible, such as `MontyExperiment` and a now-deleted Monty config that used `MontyBase`, `SensorModuleBase`, and `LearningModuleBase`. The way I got this tutorial working again was to use more a more typical setup with `MontySupervisedObjectPretrainingExperiment`, `PatchViewFinderMountHabitatDatasetArgs`, etc.
It would have been nice to use the most generic versions of these classes, but it turned out to be a bit complicated. More specifically, our class interfaces aren't totally consistent, so one class can't really be swapped out without also swapping out others. For example, `MontyBase` calls `lm.pre_episode()` without a `primary_target` …
> docs: Fix broken tutorial

- benchmarks/configs/names.py
Refactored the module to dynamically discover all experiment dataclasses using `inspect.getmembers` and `is_dataclass`. This eliminates the need for manually maintaining the list of experiment names.
- **Maintainable** – Automatically adapts to added/removed dataclasses  
- **DRY** – Removes repetitive, hardcoded logic  
- **Readable & Pythonic** – Concise, self-contained, and clear logic
This refactor improves reliability and makes the codebase easier to scale with future changes. No functional behavior was altered.
> refactor: dynamically collect experiment dataclasses and eliminate duplication

- .vale/styles/config/vocabularies/TBP/accept.txt
- docs/contributing/style-guide.md
- docs/contributing/style-guide/code-style-guide.md
- docs/hierarchy.md
This pull request incorporates [RFC 11 Code Organization Guide](https://github.com/thousandbrainsproject/tbp.monty/blob/main/rfcs/0011_code_organization_guide.md) into the code style guide in documentation.
> docs: code organization guide

- tools/generate_api_docs/source/conf.py
We're currently not including "dunder" methods, e.g. `__init__` in our generated API documentation. This changes the Sphinx configuration to include them.
> ci: update docs config to include constructors

- tests/unit/run_test.py
In #414, @dsedov reported that our import config test fails when someone checks out Monty into a path that does not include `tbp.monty`.
This pull request updates the failing test to retain the same functionality but work if the repository directory is something other than `tbp.monty`.
> test: less brittle config import test

- src/tbp/monty/__init__.py
Minor version release due to Major version 0 and breaking changes since 0.9.1.
* [breaking change] `find_transform_instance()` was removed from `transform_utils.py`
* [breaking change] `MontyBase.episodes` was removed.
* [breaking change] `MontyBase.epochs` was removed.
* [breaking change] `MontyBase.sm_ids` and `MontyBase.n_lms` were removed.
* [breaking change] `HypothesesUpdater` protocol is updated. `HypothesesUpdater.update_hypotheses` now returns `HypothesesUpdateTelemetry` in addition to the list of `ChannelHypotheses`.
* [new] `EvidenceSlopeTracker.hyp_ages`
* [new] `EvidenceSlopeTracker.calculate_slopes`
* [new] `compute_pose_errors` in `logging_utils.py`
> chore: version 0.10.0

- src/tbp/monty/frameworks/config_utils/config_args.py
- src/tbp/monty/frameworks/experiments/monty_experiment.py
- src/tbp/monty/frameworks/utils/dataclass_utils.py
- tests/unit/evidence_lm_test.py
- tests/unit/graph_learning_test.py
In the scope of #440 I noticed that we have two custom definitions of `Dataclass(Protocol)`. This pull request consolidates to one definition. I chose to use ours because the `_typeshed` `DataclassInstance` is misleading, in that (as we learned in #440), it will accept a class and an instance.
> refactor!: Dataclass class to dataclass_utils

- src/tbp/monty/__init__.py
Minor version release due to Major version 0 and breaking changes since 0.10.0.
Accessing simulator properties changed for the following properties as follows:
```diff
- sim.get_num_objects()
+ sim.num_objects
- sim.get_action_space()
+ sim.action_space
- sim.get_observations()
+ sim.observations
- sim.get_states()
+ sim.states
```
`Dataclass` type definition was moved from `src/tbp/monty/framework/config_utils/config_args.py` to `src/tbp/monty/framework/utils/dataclass_utils.py` and replaces previous `DataclassInstance` use.
> chore: version 0.11.0

- src/tbp/monty/frameworks/experiments/data_collection_experiments.py
- src/tbp/monty/frameworks/experiments/monty_experiment.py
- src/tbp/monty/frameworks/experiments/object_recognition_experiments.py
- src/tbp/monty/frameworks/experiments/pretraining_experiments.py
- src/tbp/monty/frameworks/utils/live_plotter.py
Previously the `show_sensor_output` option only worked for instances of `MontyObjectRecognitionExperiment`. However, there is nothing that prevents us from using the same feature in other `MontyExperiment` instances such as `MontySupervisedObjectPretrainingExperiment`. I moved the plotting code to the parent class and added the corresponding init and plot calls to `MontySupervisedObjectPretrainingExperiment`.
> feat: Live plotting option for all MontyExperiment instances

- src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
- src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
- tests/unit/frameworks/models/mixins/no_reset_evidence_test.py
This PR adds channel locations to the resampling telemetry in [eda1063dcf6a](https://github.com/ramyamounir/tbp.monty/commit/eda1063dcf6a780c575b8690ffe9864cb60f8764). We need this information to show the hypotheses sensor locations in the interactive plots.
The PR also introduces a breaking fix in [33e2c2f31856](https://github.com/ramyamounir/tbp.monty/commit/33e2c2f3185671c9a097353e56941937c86711d8) that moves telemetry collection until after the tracker updates. Now the evidence slopes make more sense as they make use of the latest evidence scores at every step.
> feat!: add locations to resampling telemetry

- src/tbp/monty/frameworks/models/evidence_matching/hypotheses_updater.py
- src/tbp/monty/frameworks/models/evidence_matching/learning_module.py
- src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
Until now we've allowed `ResamplingHypothesesUpdater` to use any `evidence_threshold_config`. This should not be allowed when resampling. During resampling, hypotheses are deleted instead of being excluded from updating. This PR ensures that the config specifies `evidence_threshold_config="all"` when the `ResamplingHypothesesUpdater` is being used. Otherwise, `InvalidEvidenceThresholdConfig` exception is raised.
> refactor!: ensure update of "all" hypotheses with ResamplingHypothesesUpdater
