thousandbrainsproject/tbp.monty

docs/overview/welcome-to-the-thousand-brains-project-documentation.md

Fixes the broken social icons on the welcome page in the docs.

Docs: fix broken social icons

---

docs/contributing/pull-requests.md
docs/contributing/pull-requests/contributor-license-agreement.md

Update documents to direct contributors toward the Thousand Brain Project CLA process.
This pull request also serves as the integration test for https://github.com/thousandbrainsproject/cla-assistant/pull/3 (spoiler: [it works](https://github.com/thousandbrainsproject/tbp.monty/actions/runs/12562311458/job/35022559599?pr=121))

docs: TBP CLA

---

.github/actions/vale_linter/action.yml
.github/workflows/docs.yml
README.md

This PR adds automatic vale linting to PRs and merges to main.
The files tab gets annotations where failures occur.
Also added conda caching to the docs workflow.

Tools: Vale check

---

docs/contributing/style-guide.csv
docs/contributing/style-guide.md

Adds documentation in the style.md that gives an example for inlining CSV files.
https://thousandbrainsproject.readme.io/v0.0-codeallthethingz-docs-4-tables/docs/style-guide#csv-data-tables

Docs: Inserting tables

---

docs/how-to-use-monty/getting-started.md

Adds a warning about windows/linux
https://thousandbrainsproject.readme.io/v0.0-codeallthethingz-windows-warning/docs/getting-started

Docs: Add warning about windows / linux

---

docs/contributing/style-guide.md

The GitHub Actions workflow file name is the workflow name in snake_case, e.g., `potato_stuff.yml`.

docs: document github action workflow file name convention

---

docs/how-monty-works/faq-monty.md

Docs: fix a broken link due to missing .md extension

---

.github/workflows/monty_publish.yml

Do the thing.
I added the `CONDA_TBP_REPOSITORY_TOKEN` secret to the repo.

build: publish Monty builds to anaconda.org

---

docs/contributing/documentation.md
docs/contributing/pull-requests/pull-request-flow.md
docs/figures/contributing/pull_request_flow.md
docs/snippets/edit-this-page.md
tools/github_readme_sync/readme.py
tools/github_readme_sync/tests/readme_test.py
tools/github_readme_sync/upload.py

This PR runs nh3.clean on any snippets as part of the markdown process when syncing the documentation.
It also adds an info statement to the sync process that prints out the URL to the documentation.

chore: sanitize snippets

---

src/tbp/monty/__init__.py

Minor version release as it includes a new feature of logging `GoalState` objects from https://github.com/thousandbrainsproject/tbp.monty/commit/b97460f67bf5a5577dcf3cde3a53b1a5291f56fb.

chore: version 0.1.0

---

src/tbp/monty/__init__.py

Minor version release due to Major version 0 and multiple breaking changes since 0.2.0.
No update procedure, removal of unused method.
No update procedure, removal of unused attribute.
This pull request removes motor policies from the `MotorSystem` inheritance hierarchy. 
This is a breaking change (`refactor!:`) due to configuration changes. The functionality, once configuration is updated, works the same.
A new inheritance hierarchy is introduced with `MotorPolicy` replacing `MotorSystem` at the top. The rest of the policy hierarchy remains intact.
Going forward, motor policies are an attribute of `MotorSystem` instances, specifically: `motor_system._policy`.
`MotorSystem` configuration changes as follows:
- `motor_system_class` is always now an instance of `MotorSystem`
- …

chore: version 0.3.0

---

rfcs/0000_conventional_commits.md
rfcs/0010_conventional_commits.md

Proposal to adopt conventional commits.
For easiest viewing on GitHub, use the "View file" option:

RFC 10 Conventional Commits

---

benchmarks/configs/monty_world_experiments.py
src/tbp/monty/frameworks/environment_utils/server.py
src/tbp/monty/frameworks/environments/two_d_data.py

As I was testing the monty meets world streaming experiment I noticed a few minor issues. Those are fixed here.

fix: monty meets world streaming code

---

.github/workflows/assignee-approval.yml

This adds a Github Action to check that all of the assignees on a pull request have approved it.

chore: add assignee approvals check

---

.github/actions/should_run_monty/check_changed_files.sh

ci: don't trigger monty tests when vale config changes

---

src/tbp/monty/__init__.py

Minor version release due to Major version 0 and multiple breaking changes since 0.3.0.
The removed functionality is now available in the plot tool.
No update procedure. The removed property was unused.
If you were relying on catching `ValueError`, those catches now need to be updated to catch `TypeError` instead. See ab0bed686677fc1d9914011fe18019bcd0a419d9 for specific locations to update.
If your code relied on accessing the motor system state inside policies via `self.state`, this state is no longer available on the policy. It must now be accessed from the motor system instead.
Data loader `get_good_view` now sets up and invokes `GetGoodView` positioning procedure.
The methods that implement `GetGoodView` have been removed from `InformedPolicy`. If you relied on these being present, …

chore: version 0.4.0

---

src/tbp/monty/__init__.py

Minor version release due to Major version 0 and a breaking change since 0.4.0.
The flag was unused even if set. Remove any code setting the now absent flag.

chore: version 0.5.0

---

benchmarks/configs/monty_world_habitat_experiments.py
src/tbp/monty/frameworks/environments/two_d_data.py

Just adding some minor comments around the monty meets world experiments.

docs: Add mmw comments

---

src/tbp/monty/frameworks/environments/embodied_environment.py
src/tbp/monty/simulators/habitat/environment.py
src/tbp/monty/simulators/habitat/simulator.py
src/tbp/monty/simulators/simulator.py

We're extracting a Simulator protocol that we can then use to build a MuJoCoSimulator implementation that uses the interface that we've been using in the HabitatSim class.

chore: extract Simulator protocol

---

src/tbp/monty/__init__.py

Patch version release due to no new features and no breaking changes since 0.9.0.

chore: version 0.9.1
